flags: {}

packages:
- '.'
- location:
    git: git@github.com:NCrashed/netwire.git
    commit: 7cdd2ea9d5052d8c111866fc56e6433b27962295
- location:
    git: git@github.com:NCrashed/Vec-Boolean.git
    commit: 2a29f3cdc7bbbcc99e1af96733ec8b15592484b2
- location:
    git: git@github.com:NCrashed/GPipe.git
    commit: 73458191714134eb3d8c0599142359b722cb280d
- location:
    git: git@github.com:NCrashed/OpenGL.git
    commit: a330ea7fdb1abbc36eb0d94d9f5f981b444f8e46

extra-deps: 
- Vec-1.0.5
- cereal-text-0.1.0.1
- list-tries-0.6.1
- network-transport-tcp-0.4.2
- JuicyPixels-3.2.5.3
- JuicyPixels-util-0.2
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
- GLURaw-1.5.0.2
- ObjectName-1.1.0.0
- OpenGLRaw-2.6.0.0

resolver: lts-3.12
